# This file was generated by GoReleaser. DO NOT EDIT.
cask "butler" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "12500936acd11f64bc3ba498803e6b93d9e00717babdc8276fd458968d7b43a2"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc5143058853a46da92a0caf8156abef96276acefbf5be79baf3e8b8bf3f1bd3"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d4ee50201b9454c30588177c1670dbf67ed0b0fe12d07f6e59254bed53e3bf96"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eedb523210dd3b4d3ea623e9dcf73cd60aff45f580aeff764f704a292c289c4d"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_linux_arm64.tar.gz"
    end
  end

  name "butler"
  desc "Butler Platform Engineering CLI"
  homepage "https://butler.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "butleradm"
  binary "butlerctl"

  # No zap stanza required

end
