# This file was generated by GoReleaser. DO NOT EDIT.
cask "butler" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "17292824a947f45b64c3898099999ec57af9260f923c0746ab2614b65ae75743"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d399dfa923592bbc4945e6ed535ebc201b5c1cc0a88043811f9dc647841dc7e"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da26abbac1ef32776fb86711cdcb43b2ad9edda0dd7e09bbee2b95b560893a68"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "54823316dd408cf403268b12b01aebdcb080801cabab343db46a94059eebb5f2"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_linux_arm64.tar.gz"
    end
  end

  name "butler"
  desc "Butler Platform Engineering CLI"
  homepage "https://butler.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "butleradm"
  binary "butlerctl"

  # No zap stanza required

end
