# This file was generated by GoReleaser. DO NOT EDIT.
cask "butler" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "76cd0c17efcbe073c4b9c10f040cc2a38366b917069f7969349cccec78ff3e9e"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ba455df203a8c4c04eb8b72a723e043d6a73ae1e0ccc2fcafb910cb34b5794e"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f23176b534282f9873c77b3598bf4597a818030a9d291392c5e0e008a7c96352"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf9d8396054b938b434fe90b3484620d2ec479fffba59509058b754b5a5662f5"
      url "https://github.com/butlerdotdev/butler-cli/releases/download/v#{version}/butler_linux_arm64.tar.gz"
    end
  end

  name "butler"
  desc "Butler Platform Engineering CLI"
  homepage "https://butler.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "butleradm"
  binary "butlerctl"

  # No zap stanza required

end
